language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ZMFgcQwuXWAoLOSfJTajuC7yxC4HQ1p5cd6N7i1V4RjGu93o9QlX2MUDuLQ4/8Dm6vmwi5bWKxy+/FTpCv+rIjpDfmhEiriK3qlDEnkIFK5NaO8uK81AHqOGobGk8GuQhnIG+Zxq4MaJFoJi49zvysIoEDvLiWJZo0PM84mWOz84+GLbGcQYbFnXAruCO1MwnA0mT9vA1Egh3b8hAg33KNNY6WXYcGkun8TT4sUC90VniLCa+NXeRi2UCBQ1+n2idMupNOhNcByL3ruABKwfbT2OSv26H9ez2Dv607tO4Fq/OaW9HnKBWgQoBxE5cR34g7c3YsZZHXi+bQhWdPTAmbEQASbY8hUO67HowbkM3W7WSkTgCqND0A8xQnt7TVZCoXhrmddnAVtNS1S3SM0lWQrD4kixPE+Yapv1KJlpyRhBycmq+z5id73QkOWW1Unx5KkRSEozGBkCJkKqE1XT0wF2WNHGQnRl3ZUq6ORRxqfv5D7m0AQJ8yHItPZmPQXK7ZXxqoWtG3FWe2cB1ixs6KRyLbnGq/mdFKQQ3GpzfcaXAStKF2bdD8FQBDo8Y0fGS1k7cc4oCyylvcmG887LtPhkxypipfDtquVK/evTRma41t8zVahT70rkIn7YDT4TrdSj8J7fCZd7k9pudnc2MYQKNkKA0kpRnIiHQ4NdOIE=
  app: pure-journey-69503
