language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Zq73rsNnXmZBxqRYzkZSto5hyZlCbbVCjvdQhKUvVLAuzFlruL8X4yKu9KlixgYMBKyCfefGY87TppDFADuhMuVM6ifqYa4a2GSPax4cr0j2jpKS3tQBdNuAFil2LCLNH+Fl65LA7luvNOyEZGl9wlF2SZUbvJkk6jZkYvCZMTWdY9Db2UONFRuOjaVFjOwBLnBQ/3XRUppAyNGczT3WkN9unQ/xHwWh+ioM5kvZtUPp0F9y25BNSlfNAQkroJ0sBFNM7vT09Nt1/xvLwKPNToJrHq225RMMm2Jb33xOGogrvPCmxrzVTjkMdBd+yA3sPWGRp/cViEJ3k3s/F7Z5vqBloLPuXw7KELJCV7lNU4auL/uotQ7mzDIQVscXCnTjouLxZz2z6AVQfKFDY/XRs2u8Wrr1oOfy8H2c5RegJyxCJgvpLrT/7ziY5w4A3Xapm0aad/cyAxBI/3JGRyBEfo6AbQvXE0/exGksgeShb2To3vvG1qVv56Z7RITDV+iFRyT61RARO+VSGlZUbiNBsYHO0/Akha2//Xx2L9X3uLvswHH31X7stO6sfpISZunCOmIJ1xBN2R//oMcF6JOu1dvpsyIsVn2fETLCI1HesTi7OAMpCPAGR6vUjzBTEJ3FO5A7yR7ac6L/FGuoqZnqpx0iQLmMv4Tk2hAoCGTMdso=
  app: node-tests
